### ISSUE TITLE
how to authenticate users in a new tab window opened in [Chrome|Firefox|PhantomJS] by  .click() ?

### ISSUE THREAD

**Issue by micfan** [karma-runner/karma-ng-scenario#10]
Hi, if there is a random link <a href="randomURL" target="_blank"></a>, I .click() it and pop-up new tab window, whoes domain is under www.foo.org but http://localhost:9876/ is there any way that I can authenticate user in the new window?

**Comment by vkarpov15** [comment]
not that I know of, ngScenario doesn't handle the case when you navigate the iframe away from localhost well, because browser restrictions prevent you from accessing cross-domain iframes by default.

**Comment by micfan** [comment]
So, it has no meaning to .click() something if I want to switch another browser Tab...

**Comment by vkarpov15** [comment]
I don't understand your question, can you please clarify?

**Comment by micfan** [comment]
I want open a new tab of Chrome or other Browser, can I use function `.click()` open a link?
However I has give up this test runner, thanks all the same.

**Comment by vkarpov15** [comment]
@micfan you can, but it'll be difficult to control that window through ngScenario. Typically ngScenario isn't good for testing things like oauth flows.
